kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tunnel-client-operator
subjects:
- kind: ServiceAccount
  name: tunnel-client-operator
roleRef:
  kind: Role
  name: tunnel-client-operator
  apiGroup: rbac.authorization.k8s.io
